USE [master]
GO

/****** Object:  Database [DHousingApp]    Script Date: 4/20/2019 2:21:09 AM ******/
CREATE DATABASE [DHousingApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DHousingApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DHousingApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DHousingApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DHousingApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DHousingApp] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DHousingApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DHousingApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DHousingApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DHousingApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DHousingApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DHousingApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [DHousingApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DHousingApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DHousingApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DHousingApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DHousingApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DHousingApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DHousingApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DHousingApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DHousingApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DHousingApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DHousingApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DHousingApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DHousingApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DHousingApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DHousingApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DHousingApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DHousingApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DHousingApp] SET RECOVERY FULL 
GO

ALTER DATABASE [DHousingApp] SET  MULTI_USER 
GO

ALTER DATABASE [DHousingApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DHousingApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DHousingApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DHousingApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DHousingApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DHousingApp] SET QUERY_STORE = OFF
GO

USE [DHousingApp]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DHousingApp] SET  READ_WRITE 
GO


